// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo8eFPyCn82lRGi8rrxAjzBJU81JoJlvk',
    appId: '1:115231981082:web:21b8dcfa819bc325ff9ba3',
    messagingSenderId: '115231981082',
    projectId: 'gamedonelist89',
    authDomain: 'gamedonelist89.firebaseapp.com',
    storageBucket: 'gamedonelist89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzgj7m5tM9uzzzwL13y25xYFxfxyuaPn4',
    appId: '1:115231981082:android:4b354e333378d15aff9ba3',
    messagingSenderId: '115231981082',
    projectId: 'gamedonelist89',
    storageBucket: 'gamedonelist89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBzAYgOlI4v3FZSeb2wPm9F14DbaQ7kc',
    appId: '1:115231981082:ios:96411f20c7c131d7ff9ba3',
    messagingSenderId: '115231981082',
    projectId: 'gamedonelist89',
    storageBucket: 'gamedonelist89.appspot.com',
    iosClientId: '115231981082-9b4526k07dmsthip8043ur2eh4clobql.apps.googleusercontent.com',
    iosBundleId: 'com.jacekkawiorski.gamedonelist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkBzAYgOlI4v3FZSeb2wPm9F14DbaQ7kc',
    appId: '1:115231981082:ios:89e5be1d0468cf85ff9ba3',
    messagingSenderId: '115231981082',
    projectId: 'gamedonelist89',
    storageBucket: 'gamedonelist89.appspot.com',
    iosClientId: '115231981082-hbvtpil8vuttjeji5krl26etug9jjjp7.apps.googleusercontent.com',
    iosBundleId: 'com.jacekkawiorski.gamedonelist.RunnerTests',
  );
}
